[package]
name = "kernel-node"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"]}
libbitcoinkernel-sys = { path = "../rust-bitcoinkernel/libbitcoinkernel-sys" }
env_logger = "0.10"
bitcoin = "0.32.4"
home = "0.5"
log = "0.4"
tokio = { version = "1.41", features = ["macros", "rt-multi-thread", "io-util", "net"] }
