[package]
name = "kernel-node"
version = "0.1.0"
edition = "2021"

[dependencies]
libbitcoinkernel-sys = { path = "../rust-bitcoinkernel/libbitcoinkernel-sys" }
env_logger = "0.10"
bitcoin = "0.29.2"
log = "0.4"
tokio = { version = "1.41", features = ["macros", "rt-multi-thread", "io-util", "net"] }
